---
- name: redhat | Enabling EPEL
  yum:
    name: epel
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Pre-Reqs
  yum:
    name:
      - yum-utils
    state: present
  become: true
  register: result
  until: result is successful
